# Generated by Django 4.1.7 on 2023-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_rename_emoji_tag_emoji_emojitag_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="asynctest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requestId", models.CharField(max_length=50)),
                ("tagName", models.CharField(max_length=50)),
                ("tagUrl", models.CharField(max_length=256)),
                ("img", models.BinaryField()),
                ("setNum", models.IntegerField()),
            ],
            options={"db_table": "asynctest",},
        ),
    ]
